### ISSUE TITLE
Module initialization failed for uninitialized `nuxt.options.nitro.runtimeConfig`

### ISSUE THREAD

**Issue by chriswijaya** [windx-foobar/nuxt3-notifications#7]
### Description
Followed installation step as per README.md and this error message popped up:
```
ℹ Starting setup                                                                                                         nuxt-notifications 5:13:12 pm

 ERROR  Cannot start nuxt:  Cannot convert undefined or null to object                                                                       5:13:12 pm

  at Function.assign (<anonymous>)
  at updateRuntimeConfig (node_modules/nuxt3-notifications/dist/module.mjs:9:10)
  at setup (node_modules/nuxt3-notifications/dist/module.mjs:31:5)
  at normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2112:37)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2415:95)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:4233:7)
  at async NuxtDevServer._load (node_modules/nuxi/dist/chunks/dev2.mjs:6879:5)
  at async NuxtDevServer.load (node_modules/nuxi/dist/chunks/dev2.mjs:6811:7)
  at async NuxtDevServer.init (node_modules/nuxi/dist/chunks/dev2.mjs:6806:5)
  at async Object.run (node_modules/nuxi/dist/chunks/dev-child.mjs:99:5)
```

### Impact
Nuxt app wont start

**Comment by chriswijaya** [comment]
Hey guys, love the work you've done here making `vue3-notifications` compatible with Nuxt framework 🍻 

Unfortunately I couldn't get it to work on my Nuxt project due to the above issue.
Hope the PR I raised resolve the issue for others too, otherwise please advise for a more suitable solution.

**Comment by windx-foobar** [comment]
> Hey guys, love the work you've done here making `vue3-notifications` compatible with Nuxt framework 🍻
> 
> Unfortunately I couldn't get it to work on my Nuxt project due to the above issue. Hope the PR I raised resolve the issue for others too, otherwise please advise for a more suitable solution.

Hi!
Thank u!
Can u please show me ur workspace?

Node version?
Nuxt version?

**Comment by chriswijaya** [comment]
> > Hey guys, love the work you've done here making `vue3-notifications` compatible with Nuxt framework 🍻
> > Unfortunately I couldn't get it to work on my Nuxt project due to the above issue. Hope the PR I raised resolve the issue for others too, otherwise please advise for a more suitable solution.
> 
> Hi! Thank u! Can u please show me ur workspace?
> 
> Node version? Nuxt version?

Node: v18.17.0
Nuxt: 3.11.2
Nuxt CLI: 3.11.1
Nitro: 2.9.6

It's a simple Nuxt/Vite app with below modules installed:
```
  modules: [
    '@nuxtjs/google-fonts',
    '@nuxt/image',
    'nuxt-icon',
    'nuxt3-notifications',
  ],
```

Happy to show you my workspace but not exactly sure how.

Here is my nitro content under `nuxt.options`:
```
  nitro: {
    externals: { inline: [Array] },
    virtual: {
      '#internal/dev-server-logs-options': [Function: #internal/dev-server-logs-options]
    },
    devErrorHandler: [Function: devErrorHandler],
    routeRules: {},
    typescript: { tsConfig: [Object] },
    plugins: [
      '/<path>/<to>/<project>/node_modules/nuxt/dist/core/runtime/nitro/dev-server-logs'
    ],
    publicAssets: [ [Object] ]
  },
  ```

It does not contain `runtimeConfig` property.

**Comment by windx-foobar** [comment]
> > > Hey guys, love the work you've done here making `vue3-notifications` compatible with Nuxt framework 🍻
> > > Unfortunately I couldn't get it to work on my Nuxt project due to the above issue. Hope the PR I raised resolve the issue for others too, otherwise please advise for a more suitable solution.
> > 
> > 
> > Hi! Thank u! Can u please show me ur workspace?
> > Node version? Nuxt version?
> 
> Node: v18.17.0 Nuxt: 3.11.2 Nuxt CLI: 3.11.1 Nitro: 2.9.6
> 
> It's a simple Nuxt/Vite app with below modules installed:
> 
> ```
>   modules: [
>     '@nuxtjs/google-fonts',
>     '@nuxt/image',
>     'nuxt-icon',
>     'nuxt3-notifications',
>   ],
> ```
> 
> Happy to show you my workspace but not exactly sure how.
> 
> Here is my nitro content under `nuxt.options`:
> 
> ```
>   nitro: {
>     externals: { inline: [Array] },
>     virtual: {
>       '#internal/dev-server-logs-options': [Function: #internal/dev-server-logs-options]
>     },
>     devErrorHandler: [Function: devErrorHandler],
>     routeRules: {},
>     typescript: { tsConfig: [Object] },
>     plugins: [
>       '/<path>/<to>/<project>/node_modules/nuxt/dist/core/runtime/nitro/dev-server-logs'
>     ],
>     publicAssets: [ [Object] ]
>   },
> ```
> 
> It does not contain `runtimeConfig` property.

Okey, thank u
I wiil look it today or tomorrow
